CREATE TABLE "TYPE_TABLE"
   (	"CODE" VARCHAR2(12) NOT NULL ENABLE,
	"SOURCE_ID" NUMBER NOT NULL ENABLE,
	"SOURCE_ACCOUNT" NUMBER NOT NULL ENABLE,
	"PROGRAM_ID" VARCHAR2(12),
	"TRANSACTION_DATE" DATE NOT NULL ENABLE,
	"TRANSACTION_NUMBER" NUMBER NOT NULL ENABLE,
	"VALUE" NUMBER,
	"FUNCTION" NUMBER,
	"INDICATOR" VARCHAR2(1),
	"COMMENTS" VARCHAR2(52)
   )
/
CREATE TABLE DUPLICATE_buy
   (	"CODE" VARCHAR2(12),
	"SOURCE_ID" NUMBER,
	"SOURCE_ACCOUNT" NUMBER,
	"PROGRAM_ID" VARCHAR2(12),
	"TRANSACTION_DATE" DATE,
	"TRANSACTION_NUMBER" NUMBER,
	"VALUE" NUMBER,
	"FUNCTION" NUMBER,
	"INDICATOR" VARCHAR2(1),
	"COMMENTS" VARCHAR2(52)
   )
/
CREATE TABLE DUPLICATE_sell
   (	"CODE" VARCHAR2(12),
	"SOURCE_ID" NUMBER,
	"SOURCE_ACCOUNT" NUMBER,
	"PROGRAM_ID" VARCHAR2(12),
	"TRANSACTION_DATE" DATE,
	"TRANSACTION_NUMBER" NUMBER,
	"VALUE" NUMBER,
	"FUNCTION" NUMBER,
	"INDICATOR" VARCHAR2(1),
	"COMMENTS" VARCHAR2(52)
   )
/
CREATE TABLE "MATCHED"
   (	"CODE" VARCHAR2(12),
	"SOURCE_ID" NUMBER,
	"SOURCE_ACCOUNT" NUMBER,
	"PROGRAM_ID" VARCHAR2(12),
	"TRANSACTION_DATE" DATE,
	"TRANSACTION_NUMBER" NUMBER,
	"VALUE" NUMBER,
	"FUNCTION" NUMBER,
	"INDICATOR_1" VARCHAR2(1),
	"INDICATOR_2" VARCHAR2(1),
	"COMMENTS_1" VARCHAR2(52),
	"COMMENTS_2" VARCHAR2(52),
	 CONSTRAINT "MATCHED_PK" PRIMARY KEY ("CODE", "SOURCE_ID", "SOURCE_ACCOUNT", "PROGRAM_ID", "TRANSACTION_DATE", "TRANSACTION_NUMBER", "VALUE", "FUNCTION")
   )
/
CREATE TABLE PREMATCH_buy
   (	"CODE" VARCHAR2(12),
	"SOURCE_ID" NUMBER,
	"SOURCE_ACCOUNT" NUMBER,
	"PROGRAM_ID" VARCHAR2(12),
	"TRANSACTION_DATE" DATE,
	"TRANSACTION_NUMBER" NUMBER,
	"VALUE" NUMBER,
	"FUNCTION" NUMBER,
	"INDICATOR" VARCHAR2(1),
	"COMMENTS" VARCHAR2(52),
	 CONSTRAINT "PREMATCH_1_PK" PRIMARY KEY ("CODE", "SOURCE_ID", "SOURCE_ACCOUNT", "PROGRAM_ID", "TRANSACTION_DATE", "TRANSACTION_NUMBER", "VALUE", "FUNCTION")
   )
/
CREATE TABLE PREMATCH_sell
   (	"CODE" VARCHAR2(12),
	"SOURCE_ID" NUMBER,
	"SOURCE_ACCOUNT" NUMBER,
	"PROGRAM_ID" VARCHAR2(12),
	"TRANSACTION_DATE" DATE,
	"TRANSACTION_NUMBER" NUMBER,
	"VALUE" NUMBER,
	"FUNCTION" NUMBER,
	"INDICATOR" VARCHAR2(1),
	"COMMENTS" VARCHAR2(52),
	 CONSTRAINT "PREMATCH_2_PK" PRIMARY KEY ("CODE", "SOURCE_ID", "SOURCE_ACCOUNT", "PROGRAM_ID", "TRANSACTION_DATE", "TRANSACTION_NUMBER", "VALUE", "FUNCTION")
   )
/
CREATE TABLE Programs
    (   program_id varchar2(12) not null,
        program_desc    varchar2(50)
    ) tablespace users;
CREATE TABLE functions
    (   function number not null,
        function_desc    varchar2(50)
    ) tablespace users;
CREATE TABLE sources
    (   source_id number not null,
        source_desc    varchar2(50)
    ) tablespace users;

exec dbms_stats.gather_schema_stats(user);
