CREATE TABLE
 DATE_DIM
(
 "D_DATEKEY" DATE
,"D_DATE" VARCHAR2(18)
,"D_DAYOFWEEK" VARCHAR2(10)
,"D_MONTH" VARCHAR2(9)
,"D_YEAR" NUMBER
,"D_YEARMONTHNUM" NUMBER
,"D_YEARMONTH" VARCHAR2(7)
,"D_DAYNUMINWEEK" NUMBER
,"D_DAYNUMINMONTH" NUMBER
,"D_DAYNUMINYEAR" NUMBER
,"D_MONTHNUMINYEAR" NUMBER
,"D_WEEKNUMINYEAR" NUMBER
,"D_SELLINGSEASON" VARCHAR2(12)
,"D_LASTDAYINWEEKFL" VARCHAR2(1)
,"D_LASTDAYINMONTHFL" VARCHAR2(1)
,"D_HOLIDAYFL" VARCHAR2(1)
,"D_WEEKDAYFL" VARCHAR2(1)
)
;
