CREATE TABLE
 CUSTOMER
(
 "C_CUSTKEY" NUMBER
,"C_NAME" VARCHAR2(25)
,"C_ADDRESS" VARCHAR2(25)
,"C_CITY" VARCHAR2(10)
,"C_NATION" VARCHAR2(15)
,"C_REGION" VARCHAR2(12)
,"C_PHONE" VARCHAR2(15)
,"C_MKTSEGMENT" VARCHAR2(10)
)
;
