CREATE TABLE
 LINEORDER
(
 "LO_ORDERKEY" NUMBER
,"LO_LINENUMBER" NUMBER
,"LO_CUSTKEY" NUMBER
,"LO_PARTKEY" NUMBER
,"LO_SUPPKEY" NUMBER
,"LO_ORDERDATE" DATE
,"LO_ORDERPRIORITY" VARCHAR2(15)
,"LO_SHIPPRIORITY" VARCHAR2(1)
,"LO_QUANTITY" NUMBER
,"LO_EXTENDEDPRICE" NUMBER
,"LO_ORDTOTALPRICE" NUMBER
,"LO_DISCOUNT" NUMBER
,"LO_REVENUE" NUMBER
,"LO_SUPPLYCOST" NUMBER
,"LO_TAX" NUMBER
,"LO_COMMITDATE" DATE
,"LO_SHIPMODE" VARCHAR2(10)
)
partition by range
(
 lo_commitdate
)
interval (numtoyminterval(1, 'MONTH'))
(
 partition R199201 values less than (to_date('19920201', 'YYYYMMDD'))
)
;
