CREATE TABLE
 PART
(
 "P_PARTKEY" NUMBER
,"P_NAME" VARCHAR2(22)
,"P_MFGR" VARCHAR2(6)
,"P_CATEGORY" VARCHAR2(7)
,"P_BRAND1" VARCHAR2(9)
,"P_COLOR" VARCHAR2(11)
,"P_TYPE" VARCHAR2(25)
,"P_SIZE" NUMBER
,"P_CONTAINER" VARCHAR2(10)
)
;
